/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppcomFriendAdd: typeof import('./src/components/AppcomFriendAdd.vue')['default']
    AppcomFriendList: typeof import('./src/components/AppcomFriendList.vue')['default']
    AppcomLogin: typeof import('./src/components/AppcomLogin.vue')['default']
    AppcomMessage: typeof import('./src/components/AppcomMessage.vue')['default']
    AppcomNavigator: typeof import('./src/components/AppcomNavigator.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
